package org.example.entity.enums;

public enum AdminStatus {
    START,
    MENU,
    ASK_NUMBER, CLINETS_LIST, COMMENT, SELECT_USER, SHOW_FLAYERS, SELECT_CLIENTS_CATEGORY, SHOW_FINDED_FLAYER_MENU, FLAYERS_MENU, CHANGE_REFERRALS,

}
